console.log("FreeLiberatorDx2 - A private server for SMT:Dx2 made by skompc/SquirrelDev")
console.log()
console.log("This project is still WIP! Updates will be FREQUENT!")
console.log()
console.log("I TAKE NO RESPONSIBILITY FOR ANY DAMAGE TO ANY DEVICE/DEVICES!")
console.log()
console.log("There are various ways to launch this program, I will list them now:")
console.log()
console.log("Run 'npm run help' to display this message.")
console.log()
console.log("Run 'npm run scraper' to run the asset scraper. Do this BEFORE running the asset server!")
console.log()
console.log("Run 'npm run game' to run only the logic server.")
console.log()
console.log("Run 'npm run asset' to run only the asset server.")
console.log()
console.log("Run 'npm run proxy' to run only the proxy server.")
console.log()
console.log("Run 'npm run mod-server' to run only the logic and asset servers.")
console.log()
console.log("Run 'npm run mitm-server' to run only the asset and proxy servers.")
console.log()
console.log("Run 'npm run all' to run all three servers.")
console.log()
console.log("Read the README.md file for more help.")